number_of_clips: 10
clip_length_in_frames: 30
pedestrian_distributions:
  - [['child', 'female', [1.4, 0.19], [0.9, 0.23]], 0.8]
  - ['child_male', 0.2]
camera_position_distributions:
  - [[-7.0, 2.0], [0.0, 0.25], [1.0, 0.25]]
  - [[10.0, 2.0], [0.0, 0.25], [2.0, 0.25]]
batch_size: 1
camera_fov: 110
camera_image_size: [1920, 1080]